import React from 'react';

module.exports = {
    airport: 'airport',
    autotrade: 'autotrade',
    bakery: 'bakery',
    bar: 'bar',
    beauty: 'beauty',
    beverage: 'beverage',
    brunch: 'brunch',
    carnie: 'carnie',
    cinema: 'cinema',
    coffee: 'coffee',
    education: 'education',
    entertainment: 'entertainment',
    estate: 'estate',
    finance: 'finance',
    gallery: 'gallery',
    gym: 'gym',
    health: 'health',
    hotel: 'hotel',
    household: 'household',
    immigration: 'immigration',
    living: 'living',
    mall: 'mall',
    market: 'market',
    media: 'media',
    museum: 'museum',
    pastry: 'pastry',
    rental: 'rental',
    restaurant: 'restaurant',
    secondhand: 'secondhand',
    retail: 'retail',
    spa: 'spa',
    stadium: 'stadium',
    studio: 'studio',
    tax: 'tax',
    theater: 'theater',
    tourism: 'tourism',
    training: 'training',
    views: 'views',
    outdooor: 'outdoor',
};
