import React from 'react';

module.exports = {
    description: {
        type: 'textarea',
        required: false,
        label: 'common.description',
    },
    name: {
        type: 'text',
        required: true,
        label: 'common.title',
    },
    seller: {
        type: 'choice',
        required: true,
        label: 'autotrade.seller',
        multiple: false,
        choices: {
            'autotrade.seller.private': 'private',
            'autotrade.seller.dealer': 'dealer',
            'autotrade.seller.used-dealer': 'used-dealer',
        },
    },
    condition: {
        type: 'choice',
        required: true,
        label: 'autotrade.condition',
        multiple: false,
        choices: {
            'autotrade.condition.used': 'used',
            'autotrade.condition.transfer': 'transfer',
            'autotrade.condition.new': 'new',
        },
    },
    total_price: {
        type: 'number',
        required: false,
        label: 'autotrade.total_price',
    },
    mileage: {
        type: 'number',
        required: false,
        label: 'autotrade.mileage',
    },
    payment_price: {
        type: 'number',
        required: false,
        label: 'autotrade.payment_price',
    },
    payment_frequency: {
        type: 'choice',
        required: false,
        label: 'autotrade.payment_frequency',
        multiple: false,
        choices: {
            'autotrade.payment_frequency.weekly': 'weekly',
            'autotrade.payment_frequency.bi-weekly': 'bi-weekly',
            'autotrade.payment_frequency.monthly': 'monthly',
            'autotrade.payment_frequency.quarterly': 'quarterly',
            'autotrade.payment_frequency.yearly': 'yearly',
        },
    },
    payment_term: {
        type: 'choice',
        required: false,
        label: 'autotrade.payment_term',
        multiple: false,
        choices: {
            'autotrade.payment_term.12': '12',
            'autotrade.payment_term.24': '24',
            'autotrade.payment_term.36': '36',
            'autotrade.payment_term.48': '48',
            'autotrade.payment_term.60': '60',
            'autotrade.payment_term.72': '72',
            'autotrade.payment_term.84': '84',
            'autotrade.payment_term.96': '96',
        },
    },
    make: {
        type: 'choice',
        required: true,
        label: 'autotrade.make',
        multiple: false,
        choices: {
            'autotrade.make.acura': 'acura',
            'autotrade.make.audi': 'audi',
            'autotrade.make.bmw': 'bmw',
            'autotrade.make.buick': 'buick',
            'autotrade.make.cadillac': 'cadillac',
            'autotrade.make.chevrolet': 'chevrolet',
            'autotrade.make.chrysler': 'chrysler',
            'autotrade.make.dodge': 'dodge',
            'autotrade.make.ferrari': 'ferrari',
            'autotrade.make.ford': 'ford',
            'autotrade.make.gmc': 'gmc',
            'autotrade.make.honda': 'honda',
            'autotrade.make.hummer': 'hummer',
            'autotrade.make.hyundai': 'hyundai',
            'autotrade.make.infiniti': 'infiniti',
            'autotrade.make.jaguar': 'jaguar',
            'autotrade.make.jeep': 'jeep',
            'autotrade.make.kia': 'kia',
            'autotrade.make.land-rover': 'land-rover',
            'autotrade.make.lexus': 'lexus',
            'autotrade.make.lincoln': 'lincoln',
            'autotrade.make.maserati': 'maserati',
            'autotrade.make.mazda': 'mazda',
            'autotrade.make.mercedes-amg': 'mercedes-amg',
            'autotrade.make.mercedes-benz': 'mercedes-benz',
            'autotrade.make.mini': 'mini',
            'autotrade.make.mitsubishi': 'mitsubishi',
            'autotrade.make.mustang': 'mustang',
            'autotrade.make.nissan': 'nissan',
            'autotrade.make.pontiac': 'pontiac',
            'autotrade.make.porsche': 'porsche',
            'autotrade.make.ram': 'ram',
            'autotrade.make.smart': 'smart',
            'autotrade.make.subaru': 'subaru',
            'autotrade.make.suzuki': 'suzuki',
            'autotrade.make.tesla': 'tesla',
            'autotrade.make.toyota': 'toyota',
            'autotrade.make.volkswagen': 'volkswagen',
            'autotrade.make.volvo': 'volvo',
            'autotrade.make.other': 'other',
        },
    },
    year: {
        type: 'date',
        required: true,
        label: 'autotrade.year',
    },
    model: {
        type: 'text',
        required: true,
        label: 'autotrade.model',
    },
    body_type: {
        type: 'choice',
        required: true,
        label: 'autotrade.body_type',
        multiple: false,
        choices: {
            'autotrade.body_type.sedan': 'sedan',
            'autotrade.body_type.coupe': 'coupe',
            'autotrade.body_type.roadster': 'roadster',
            'autotrade.body_type.suv': 'suv',
            'autotrade.body_type.minivan': 'minivan',
            'autotrade.body_type.truck': 'truck',
            'autotrade.body_type.other': 'other',
        },
    },
    engine: {
        type: 'choice',
        required: true,
        label: 'autotrade.engine',
        multiple: false,
        choices: {
            'autotrade.engine.4': '4',
            'autotrade.engine.6': '6',
            'autotrade.engine.8': '8',
            'autotrade.engine.12': '12',
            'autotrade.engine.other': 'other',
        },
    },
    transmission: {
        type: 'choice',
        required: true,
        label: 'autotrade.transmission',
        multiple: false,
        choices: {
            'autotrade.transmission.automatic': 'automatic',
            'autotrade.transmission.manual': 'manual',
            'autotrade.transmission.tiptronic': 'tiptronic',
            'autotrade.transmission.other': 'other',
        },
    },
    drivetrain: {
        type: 'choice',
        required: true,
        label: 'autotrade.drivetrain',
        multiple: false,
        choices: {
            'autotrade.drivetrain.all-wheel-drive': 'all-wheel-drive',
            'autotrade.drivetrain.four-wheel-drive': 'four-wheel-drive',
            'autotrade.drivetrain.front-wheel-drive': 'front-wheel-drive',
            'autotrade.drivetrain.rear-wheel-drive': 'rear-wheel-drive',
            'autotrade.drivetrain.other': 'other',
        },
    },
    fuel_type: {
        type: 'choice',
        required: true,
        label: 'autotrade.fuel_type',
        multiple: false,
        choices: {
            'autotrade.fuel_type.gasoline': 'gasoline',
            'autotrade.fuel_type.flex-fuel': 'flex-fuel',
            'autotrade.fuel_type.electric': 'electric',
            'autotrade.fuel_type.diesel': 'diesel',
            'autotrade.fuel_type.other': 'other',
        },
    },
    seating: {
        type: 'choice',
        required: true,
        label: 'autotrade.seating',
        multiple: false,
        choices: {
            'autotrade.seating.2': '2',
            'autotrade.seating.4': '4',
            'autotrade.seating.5': '5',
            'autotrade.seating.7': '7',
            'autotrade.seating.other': 'other',
        },
    },
    doors: {
        type: 'choice',
        required: true,
        label: 'autotrade.doors',
        multiple: false,
        choices: {
            'autotrade.doors.2': '2',
            'autotrade.doors.4': '4',
            'autotrade.doors.other': 'other',
        },
    },
};
