import React from 'react';

module.exports = {
    name: {
        type: 'text',
        required: true,
        label: 'common.title',
    },
    avarage: {
        type: 'choice',
        required: true,
        label: 'common.avarage',
        choices: {
            'common.avarage.one': 'one',
            'common.avarage.two': 'two',
            'common.avarage.three': 'three',
            'common.avarage.four': 'four',
        },
        multiple: false,
    },
    cuisine: {
        type: 'choice',
        required: true,
        label: 'common.cuisine',
        choices: {
            'cuisine.french': 'french',
            'cuisine.italian': 'italian',
            'cuisine.spanish': 'spanish',
            'cuisine.swiss': 'swiss',
            'cuisine.belgian': 'belgian',
            'cuisine.german': 'german',
            'cuisine.russian': 'russian',
            'cuisine.canadian': 'canadian',
            'cuisine.quebecois': 'quebecois',
            'cuisine.american': 'american',
            'cuisine.mexican': 'mexican',
            'cuisine.colombian': 'colombian',
            'cuisine.chilean': 'chilean',
            'cuisine.chinese': 'chinese',
            'cuisine.fondue': 'fondue',
            'cuisine.cantonese': 'cantonese',
            'cuisine.taiwanese': 'taiwanese',
            'cuisine.japanese': 'japanese',
            'cuisine.korean': 'korean',
            'cuisine.thai': 'thai',
            'cuisine.vietnamese': 'vietnamese',
            'cuisine.asian': 'asian',
            'cuisine.mongolian': 'mongolian',
            'cuisine.indian': 'indian',
            'cuisine.middle-eastern': 'middle-eastern',
            'cuisine.african': 'african',
            'cuisine.coffee': 'coffee',
            'cuisine.bakery': 'bakery',
            'cuisine.sandwich': 'sandwich',
            'cuisine.burger': 'burger',
            'cuisine.ice-cream': 'ice-cream',
            'cuisine.pizza': 'pizza',
            'cuisine.bbq': 'bbq',
            'cuisine.grill': 'grill',
            'cuisine.brasserie': 'brasserie',
            'cuisine.steak': 'steak',
            'cuisine.seafood': 'seafood',
            'cuisine.poutine': 'poutine',
            'cuisine.ramen': 'ramen',
            'cuisine.sushi': 'sushi',
            'cuisine.deli': 'deli',
            'cuisine.fish-chips': 'fish-chips',
            'cuisine.tapas': 'tapas',
            'cuisine.finger-food': 'finger-food',
            'cuisine.yogurt': 'yogurt',
            'cuisine.desserts': 'desserts',
            'cuisine.salad': 'salad',
            'cuisine.soups': 'soups',
        },
        multiple: false,
    },
    meals: {
        type: 'choice',
        required: true,
        label: 'restaurant.meals',
        choices: {
            'restaurant.meals.breakfast': 'breakfast',
            'restaurant.meals.brunch': 'brunch',
            'restaurant.meals.lunch': 'lunch',
            'restaurant.meals.dinner': 'dinner',
        },
        multiple: true,
    },
    description: {
        type: 'textarea',
        required: false,
        label: 'common.description',
    },
};
