import React from 'react';

module.exports = {
    name: {
        type: 'text',
        required: true,
        label: 'common.title',
    },
    price: {
        type: 'number',
        required: false,
        label: 'common.price',
    },
    category: {
        type: 'choice',
        required: true,
        label: 'secondhand.category.label',
        choices: {
            'secondhand.category.household': 'household',
            'secondhand.category.kitchenware': 'kitchenware',
            'secondhand.category.appliances': 'appliances',
            'secondhand.category.tool': 'tool',
            'secondhand.category.garden': 'garden',
            'secondhand.category.pet': 'pet',
            'secondhand.category.miscellaneous': 'miscellaneous',
            'secondhand.category.jewelry': 'jewelry',
            'secondhand.category.cosmetic': 'cosmetic',
            'secondhand.category.glasses': 'glasses',
            'secondhand.category.luggage': 'luggage',
            'secondhand.category.clothing_female': 'clothing_female',
            'secondhand.category.clothing_male': 'clothing_male',
            'secondhand.category.wedding_clothing': 'wedding_clothing',
            'secondhand.category.wedding_jewelry': 'wedding_jewelry',
            'secondhand.category.mobile': 'mobile',
            'secondhand.category.electronics': 'electronics',
            'secondhand.category.network': 'network',
            'secondhand.category.maternal': 'maternal',
            'secondhand.category.toy': 'toy',
            'secondhand.category.sport': 'sport',
            'secondhand.category.photographic': 'photographic',
            'secondhand.category.audio': 'audio',
            'secondhand.category.auto_part': 'auto_part',
            'secondhand.category.bicycle': 'bicycle',
            'secondhand.category.antique': 'antique',
            'secondhand.category.musical': 'musical',
            'secondhand.category.art': 'art',
            'secondhand.category.ticket': 'ticket',
            'secondhand.category.video_game': 'video_game',
            'secondhand.category.book': 'book',
            'secondhand.category.health': 'health',
            'secondhand.category.alcohol': 'alcohol',
        },
        multiple: false,
    },
    description: {
        type: 'textarea',
        required: false,
        label: 'common.description',
    },
};
