import React from 'react';

module.exports = {
    name: {
        type: 'text',
        required: true,
        label: 'common.title',
    },
    price: {
        type: 'number',
        required: false,
        label: 'common.price',
    },
    category: {
        type: 'choice',
        required: true,
        label: 'common.category',
        multiple: false,
        choices: {
            'training.category.language': 'language',
            'training.category.art': 'art',
            'training.category.sport': 'sport',
            'training.category.health': 'health',
            'training.category.it': 'it',
            'training.category.junior_senior': 'junior_senior',
        },
    },
    sub_category: {
        type: 'choice',
        required: true,
        label: 'common.category',
        multiple: false,
        choices: {
            language: {
                'training.sub_category.language.french': 'french',
                'training.sub_category.language.english': 'english',
                'training.sub_category.language.arabic': 'arabic',
                'training.sub_category.language.spanish': 'spanish',
                'training.sub_category.language.russian': 'russian',
                'training.sub_category.language.german': 'german',
                'training.sub_category.language.italian': 'italian',
                'training.sub_category.language.mandarin': 'mandarin',
                'training.sub_category.language.cantonese': 'cantonese',
                'training.sub_category.language.japanese': 'japanese',
                'training.sub_category.language.korean': 'korean',
                'training.sub_category.language.other': 'other',
            },
            art: {
                'training.sub_category.art.music': 'music',
                'training.sub_category.art.dance': 'dance',
                'training.sub_category.art.painting': 'painting',
                'training.sub_category.art.photography': 'photography',
                'training.sub_category.art.piano': 'piano',
                'training.sub_category.art.violin': 'violin',
                'training.sub_category.art.other': 'other',
            },
            sport: {
                'training.sub_category.sport.hockey': 'hockey',
                'training.sub_category.sport.lacrosse': 'lacrosse',
                'training.sub_category.sport.ski': 'ski',
                'training.sub_category.sport.football': 'football',
                'training.sub_category.sport.baseball': 'baseball',
                'training.sub_category.sport.basketball': 'basketball',
                'training.sub_category.sport.tennis': 'tennis',
                'training.sub_category.sport.badminton': 'badminton',
                'training.sub_category.sport.golf': 'golf',
                'training.sub_category.sport.boxing': 'boxing',
                'training.sub_category.sport.swiming': 'swiming',
                'training.sub_category.sport.curling': 'curling',
                'training.sub_category.sport.other': 'other',
            },
            health: {
                'training.sub_category.health.gym': 'gym',
                'training.sub_category.health.yoga': 'yoga',
                'training.sub_category.health.massage': 'massage',
            },
            it: {
                'training.sub_category.it.web': 'web',
                'training.sub_category.it.software': 'software',
                'training.sub_category.it.networking': 'networking',
                'training.sub_category.it.database': 'database',
                'training.sub_category.it.ai': 'ai',
                'training.sub_category.it.qa': 'qa',
                'training.sub_category.it.design': 'design',
                'training.sub_category.it.other': 'other',
            },
            junior_senior: {
                'training.sub_category.junior_senior.junior': 'junior',
                'training.sub_category.junior_senior.senior': 'senior',
            },
        },
    },
    description: {
        type: 'textarea',
        required: false,
        label: 'common.description',
    },
};
